all:
	mpicxx -std=c++11 -I/usr/local/fftw/include -L/usr/local/fftw/lib -lfftw -lm ERROR.h IOSets.cpp IOSets.h Main.cpp MatlabVector.cpp MatlabVector.h minitypes.h normpdf_checked.h SolveIterSym.cpp Fourier.cpp
