all:

	mpicxx -std=c++11 -lmkl_intel_ilp64 -lmkl_core -lmkl_sequential -static-libgcc -static-libstdc++ ERROR.h IOSets.cpp IOSets.h Main.cpp MatlabVector.cpp MatlabVector.h minitypes.h normpdf_checked.h SolveIterSym.cpp Fourier.cpp